"""
bios_preservation.py — Master launcher

Lives at the root of the bios_preservation/ folder.
Finds configuration in  ./configure/bios_preservation.conf
Uses user overrides from ./configure/bios_preservation_user.conf  (if present)
Imports scripts from    ./scripts/

Interactive usage (no arguments):
  python bios_preservation.py

Command-line usage:
  python bios_preservation.py update
  python bios_preservation.py build
  python bios_preservation.py stage
  python bios_preservation.py update build stage
  python bios_preservation.py update build stage --continue-on-error
"""

from __future__ import annotations

import argparse
import configparser
import os
import sys
import traceback
from pathlib import Path

VALID_STEPS = ("update", "build", "stage", "report")

# Menu entries: (display label, step key)
MENU_ITEMS = [
    ("Update",    "update"),
    ("Build",     "build"),
    ("Stage",     "stage"),
    ("Report",    "report"),
    ("Backup",    "backup"),
    ("Dump",      "dump"),
    ("Configure", "configure"),
]


# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------

def _persist_unrar_tool(path: str, base_dir: Path) -> None:
    """Save the unrar tool path to bios_preservation_user.conf so it persists across runs."""
    import configparser
    user_conf = base_dir / "configure" / "bios_preservation_user.conf"
    cfg = configparser.ConfigParser()
    if user_conf.exists():
        cfg.read(str(user_conf), encoding="utf-8")
    if not cfg.has_section("build"):
        cfg.add_section("build")
    cfg.set("build", "unrar_tool", path)
    user_conf.parent.mkdir(parents=True, exist_ok=True)
    with open(user_conf, "w", encoding="utf-8") as fh:
        fh.write("# bios_preservation_user.conf\n")
        fh.write("# Generated by bios_configure.py / bios_build.py\n")
        fh.write("# Delete this file to restore defaults.\n\n")
        cfg.write(fh)
    print(f"  Saved to: {user_conf}")


def _check_dependencies(base_dir: Path) -> None:
    """
    Check for required Python packages and the UnRAR binary.
    Offer to install missing Python packages via pip.
    Prints a warning (but does not abort) if anything is missing.
    """
    import importlib
    import subprocess

    PYTHON_DEPS = [
        ("yaml",   "pyyaml",  "PyYAML  — YAML parsing (required for Step 1: Update)"),
        ("py7zr",  "py7zr",   "py7zr   — 7z archive support (required for .7z sources)"),
        ("rarfile","rarfile",  "rarfile — RAR archive support (required for .rar sources)"),
    ]

    missing_packages: list[tuple[str, str, str]] = []
    for import_name, pip_name, description in PYTHON_DEPS:
        try:
            importlib.import_module(import_name)
        except ImportError:
            missing_packages.append((import_name, pip_name, description))

    # Only check for the unrar binary if rarfile itself is installed —
    # let rarfile do its own detection since it knows all the right paths.
    missing_unrar = False
    unrar_tool_path = "unrar"
    if "rarfile" not in [p[0] for p in missing_packages]:
        try:
            import rarfile
            unrar_tool_path = getattr(rarfile, "UNRAR_TOOL", "unrar")
            try:
                subprocess.run(
                    [unrar_tool_path],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except (FileNotFoundError, OSError):
                missing_unrar = True
        except Exception:
            missing_unrar = True

    if not missing_packages and not missing_unrar:
        return  # everything present — silent

    print(f"\n{'='*60}")
    print("  DEPENDENCY CHECK")
    print("─" * 60)

    if missing_packages:
        print("\n  Missing Python packages:\n")
        for _, pip_name, description in missing_packages:
            print(f"    • {description}")

    if missing_unrar:
        print("\n  Missing binary:\n")
        print(f"    • UnRAR — required for .rar archive support")
        print(f"      rarfile is looking for: {unrar_tool_path!r}")
        print(f"      If WinRAR is installed, enter its UnRAR.exe path below to fix this.")
        print(f"      Common location: C:\\Program Files\\WinRAR\\UnRAR.exe")
        print(f"      To install: winget install RARLab.WinRAR  (Windows)")
        print(f"                  brew install rar              (macOS)")
        print(f"                  sudo apt install unrar        (Linux)")
        print()
        raw = input("  Enter path to UnRAR.exe (or Enter to skip): ").strip().strip('"').strip("'")
        if raw:
            # Verify the path actually works
            try:
                subprocess.run(
                    [raw],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                # If we get here without FileNotFoundError, it works — save it
                import rarfile as _rf
                _rf.UNRAR_TOOL = raw
                # Also persist to user conf so it survives restarts
                _persist_unrar_tool(raw, base_dir)
                print(f"  UnRAR path set to: {raw!r}")
                missing_unrar = False
            except (FileNotFoundError, OSError):
                print(f"  Could not launch {raw!r} — path not saved.")

    if missing_packages:
        print()
        raw = input("  Install missing Python packages now via pip? [Y/N]: ").strip().lower()
        if raw in ("y", ""):
            import subprocess
            pip_names = [p for _, p, _ in missing_packages]
            cmd = [sys.executable, "-m", "pip", "install"] + pip_names
            print(f"\n  Running: {' '.join(cmd)}\n")
            result = subprocess.run(cmd)
            if result.returncode == 0:
                print("\n  Packages installed successfully.")
            else:
                print("\n  pip install failed — please install manually.")
        else:
            print("  Skipping — some features may not work.")

    print()


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def _load_config(base_dir: Path) -> configparser.ConfigParser:
    conf_path = base_dir / "configure" / "bios_preservation.conf"
    if not conf_path.exists():
        print(f"ERROR: configuration file not found: {conf_path}")
        print("Expected location: <bios_preservation>/configure/bios_preservation.conf")
        sys.exit(1)
    cfg = configparser.ConfigParser()
    # Load default conf first, then overlay user conf if present
    paths = [str(conf_path)]
    user_conf = base_dir / "configure" / "bios_preservation_user.conf"
    if user_conf.exists():
        paths.append(str(user_conf))
        print(f"[launcher] Using user configuration: {user_conf}")
    cfg.read(paths, encoding="utf-8")
    return cfg


# ---------------------------------------------------------------------------
# File-open checks
# ---------------------------------------------------------------------------

def _file_is_locked(path: str) -> bool:
    """Return True if *path* exists and cannot be opened exclusively for writing."""
    if not os.path.exists(path):
        return False
    try:
        with open(path, "a+b"):
            return False
    except OSError:
        return True


def _files_to_check(step: str, config: configparser.ConfigParser, base_dir: str) -> list[str]:
    """Return the list of file paths to check for locks before running *step*."""
    def r(rel: str) -> str:
        p = Path(rel)
        return str(p if p.is_absolute() else Path(base_dir) / p)

    if step == "update":
        out = config.get("update", "output_dir", fallback="update")
        return [
            r(f"{out}/combined_platform_manifest.json"),
            r(f"{out}/combined_platform_manifest.csv"),
        ]

    if step == "build":
        sqlar = config.get("build", "sqlar_output",  fallback="build/bios_database.sqlar")
        jout  = config.get("build", "json_output",   fallback="build/combined_platform_build.json")
        cout  = config.get("build", "csv_output",    fallback="build/combined_platform_build.csv")
        return [r(sqlar), r(jout), r(cout)]

    if step == "stage":
        sqlar = config.get("stage", "sqlar_input",    fallback="build/bios_database.sqlar")
        mf    = config.get("stage", "manifest_input", fallback="build/combined_platform_build.json")
        return [r(sqlar), r(mf)]

    if step == "report":
        sqlar = config.get("report", "sqlar_input",    fallback="build/bios_database.sqlar")
        mf    = config.get("report", "manifest_input", fallback="build/combined_platform_build.json")
        rdir  = config.get("report", "report_dir",     fallback="report")
        platforms = [
            "retrodeck", "retropie", "batocera", "emudeck",
            "recalbox",  "retrobat", "lakka",    "retroarch",
        ]
        enabled_csvs = [
            r(f"{rdir}/{p}_report.csv")
            for p in platforms
            if config.get("report", p, fallback="yes").strip().lower() in ("yes", "true", "1")
        ]
        return [r(sqlar), r(mf)] + enabled_csvs

    if step in ("backup", "dump"):
        sqlar = config.get("build", "sqlar_output", fallback="build/bios_database.sqlar")
        return [r(sqlar)]

    # configure has no file-lock check
    return []


def _check_files_open(step: str, config: configparser.ConfigParser, base_dir: str) -> bool:
    """
    Check whether any files relevant to *step* are currently locked.
    Returns True if all clear, False if any file is locked.
    """
    locked = [f for f in _files_to_check(step, config, base_dir) if _file_is_locked(f)]
    if locked:
        print(f"\n  ERROR: the following file(s) are open in another application.")
        print(f"  Please close them before running {step.upper()}:\n")
        for f in locked:
            print(f"    {f}")
        print()
        return False
    return True


# ---------------------------------------------------------------------------
# Step runner
# ---------------------------------------------------------------------------

def _run_step(step: str, config: configparser.ConfigParser, base_dir: str) -> bool:
    """Import and run the named step.  Returns True on success."""
    print(f"\n{'='*60}")
    print(f"  STEP: {step.upper()}")
    print(f"{'='*60}")
    try:
        if step == "update":
            import bios_update
            return bios_update.run(config, base_dir)
        elif step == "build":
            import bios_build
            return bios_build.run(config, base_dir)
        elif step == "stage":
            import bios_stage
            return bios_stage.run(config, base_dir)
        elif step == "report":
            import bios_report
            return bios_report.run(config, base_dir)
        elif step == "backup":
            import bios_backup
            return bios_backup.run(config, base_dir)
        elif step == "dump":
            import bios_dump
            return bios_dump.run(config, base_dir)
        elif step == "configure":
            import bios_configure
            return bios_configure.run(config, base_dir)
        else:
            print(f"ERROR: unknown step {step!r}")
            return False
    except Exception:
        print(f"\nERROR: unhandled exception in step {step!r}:")
        traceback.print_exc()
        return False


def _print_summary(results: dict[str, bool], steps: list[str]) -> None:
    print(f"\n{'='*60}")
    print("  SUMMARY")
    print(f"{'='*60}")
    for step in steps:
        if step in results:
            mark = "OK  ✓" if results[step] else "FAILED ✗"
            print(f"  {step:12s}  {mark}")
        else:
            print(f"  {step:12s}  skipped")
    print()


# ---------------------------------------------------------------------------
# Interactive menu
# ---------------------------------------------------------------------------

def _run_interactive(base_dir: Path, scripts_dir: Path) -> None:
    scripts_str = str(scripts_dir)
    if scripts_str not in sys.path:
        sys.path.insert(0, scripts_str)

    config = _load_config(base_dir)

    while True:
        print(f"\n{'='*60}")
        print("  BIOS Preservation Tool")
        print(f"{'='*60}")
        for i, (label, _) in enumerate(MENU_ITEMS, start=1):
            print(f"  {i}. {label}")
        print(f"  0. Exit")
        print(f"{'─'*60}")

        raw = input("  Enter number: ").strip()

        if raw == "0":
            print("  Goodbye.")
            sys.exit(0)

        if not raw.isdigit() or not (1 <= int(raw) <= len(MENU_ITEMS)):
            print(f"  Invalid selection. Please enter a number between 0 and {len(MENU_ITEMS)}.")
            continue

        choice      = int(raw)
        label, step = MENU_ITEMS[choice - 1]

        # File-open check (configure has none)
        if not _check_files_open(step, config, str(base_dir)):
            continue

        # Run the step and show summary, then loop back to menu
        success = _run_step(step, config, str(base_dir))

        # After configure completes, reload config in case user.conf was
        # created, updated, or deleted
        if step == "configure":
            config = _load_config(base_dir)

        _print_summary({step: success}, [step])


# ---------------------------------------------------------------------------
# CLI (arguments provided)
# ---------------------------------------------------------------------------

def _run_cli(base_dir: Path, scripts_dir: Path) -> None:
    parser = argparse.ArgumentParser(
        prog="bios_preservation.py",
        description="BIOS Preservation — master launcher",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Steps:
  update     Parse platform YAMLs -> update/combined_platform_manifest.*
  build      Scan sources, build database -> build/bios_database.sqlar + build/combined_platform_build.*
  stage      Stage files per platform -> stage/<platform>/
  report     Generate per-platform status reports -> report/<platform>_report.csv

Examples:
  python bios_preservation.py update
  python bios_preservation.py build
  python bios_preservation.py stage
  python bios_preservation.py update build stage
  python bios_preservation.py update build stage --continue-on-error
        """,
    )
    parser.add_argument(
        "steps",
        nargs="+",
        choices=VALID_STEPS,
        metavar="STEP",
        help=f"One or more steps: {', '.join(VALID_STEPS)}",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        default=False,
        help="Continue to the next step even if a step fails",
    )

    args = parser.parse_args()

    # Deduplicate while preserving order
    seen:  set[str]  = set()
    steps: list[str] = []
    for s in args.steps:
        if s not in seen:
            steps.append(s)
            seen.add(s)

    scripts_str = str(scripts_dir)
    if scripts_str not in sys.path:
        sys.path.insert(0, scripts_str)

    config = _load_config(base_dir)

    results:    dict[str, bool] = {}
    overall_ok: bool = True

    for step in steps:
        if not _check_files_open(step, config, str(base_dir)):
            results[step] = False
            overall_ok = False
            if not args.continue_on_error:
                print(f"[launcher] Step {step!r} aborted (file locked) — stopping.")
                print("[launcher] Use --continue-on-error to run subsequent steps anyway.")
                break
            else:
                print(f"[launcher] Step {step!r} aborted (file locked) — continuing (--continue-on-error).")
            continue

        success = _run_step(step, config, str(base_dir))
        results[step] = success
        if not success:
            overall_ok = False
            if not args.continue_on_error:
                print(f"\n[launcher] Step {step!r} FAILED — stopping.")
                print("[launcher] Use --continue-on-error to run subsequent steps anyway.")
                break
            else:
                print(f"\n[launcher] Step {step!r} FAILED — continuing (--continue-on-error).")

    _print_summary(results, steps)
    sys.exit(0 if overall_ok else 1)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _apply_unrar_tool(base_dir: Path) -> None:
    """
    Set rarfile.UNRAR_TOOL to the right binary, in priority order:
      1. Path saved in bios_preservation_user.conf  (user already resolved it)
      2. Well-known default install locations (WinRAR on Windows)
      3. Leave as-is (rarfile's own default, usually just 'unrar' on PATH)
    """
    try:
        import rarfile

        # ── 1. User-saved path from conf ──────────────────────────────────
        user_conf = base_dir / "configure" / "bios_preservation_user.conf"
        if user_conf.exists():
            cfg = configparser.ConfigParser()
            cfg.read(str(user_conf), encoding="utf-8")
            tool = cfg.get("build", "unrar_tool", fallback="").strip()
            if tool and Path(tool).exists():
                rarfile.UNRAR_TOOL = tool
                return

        # ── 2. Well-known default locations ───────────────────────────────
        FALLBACK_PATHS = [
            r"C:\Program Files\WinRAR\UnRAR.exe",
            r"C:\Program Files (x86)\WinRAR\UnRAR.exe",
        ]
        for candidate in FALLBACK_PATHS:
            if Path(candidate).exists():
                rarfile.UNRAR_TOOL = candidate
                return

        # ── 3. Leave rarfile's default in place ───────────────────────────

    except Exception:
        pass


def main() -> None:
    base_dir    = Path(__file__).resolve().parent
    scripts_dir = base_dir / "scripts"

    if not scripts_dir.is_dir():
        print(f"ERROR: scripts directory not found: {scripts_dir}")
        print("Expected: <bios_preservation>/scripts/")
        sys.exit(1)

    # Apply saved/default unrar_tool path before dependency check runs
    _apply_unrar_tool(base_dir)

    _check_dependencies(base_dir)

    if sys.argv[1:]:
        _run_cli(base_dir, scripts_dir)
    else:
        _run_interactive(base_dir, scripts_dir)


if __name__ == "__main__":
    main()
